package com.example.android0128.trainingmvp.tests;


import android.support.annotation.NonNull;
import android.support.test.InstrumentationRegistry;
import android.support.test.espresso.ViewInteraction;
import android.support.test.rule.ActivityTestRule;
import android.support.test.runner.AndroidJUnit4;
import android.test.suitebuilder.annotation.LargeTest;
import android.view.View;
import android.view.ViewGroup;
import android.view.ViewParent;

import com.example.android0128.trainingmvp.R;
import com.example.android0128.trainingmvp.data.usecase.FavoriteCharacters;
import com.example.android0128.trainingmvp.data.usecase.GetCharacters;
import com.example.android0128.trainingmvp.presentation.NavigationActivity;
import com.example.android0128.trainingmvp.presentation.models.Character;
import com.example.android0128.trainingmvp.rules.MockWebServerRule;
import com.example.android0128.trainingmvp.rules.NeedsMockWebServer;
import com.example.android0128.trainingmvp.screens.ItemsScreen;
import com.google.common.collect.Lists;

import org.hamcrest.Description;
import org.hamcrest.Matcher;
import org.hamcrest.TypeSafeMatcher;
import org.hamcrest.core.IsInstanceOf;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.RuleChain;
import org.junit.runner.RunWith;
import org.mockito.Mockito;

import java.util.List;

import io.reactivex.Observable;
import okhttp3.mockwebserver.MockResponse;
import okhttp3.mockwebserver.MockWebServer;

import static android.support.test.espresso.Espresso.onView;
import static android.support.test.espresso.Espresso.pressBack;
import static android.support.test.espresso.action.ViewActions.click;
import static android.support.test.espresso.action.ViewActions.scrollTo;
import static android.support.test.espresso.action.ViewActions.swipeLeft;
import static android.support.test.espresso.action.ViewActions.swipeRight;
import static android.support.test.espresso.assertion.ViewAssertions.matches;
import static android.support.test.espresso.contrib.RecyclerViewActions.actionOnItemAtPosition;
import static android.support.test.espresso.matcher.ViewMatchers.isDisplayed;
import static android.support.test.espresso.matcher.ViewMatchers.withId;
import static android.support.test.espresso.matcher.ViewMatchers.withParent;
import static android.support.test.espresso.matcher.ViewMatchers.withText;
import static org.hamcrest.Matchers.allOf;
import static org.mockito.Mockito.when;

/**
 * Test for Characters functionality.
 * Base autogenerated with Espresso Test Recorder.
 */
@LargeTest
@RunWith(AndroidJUnit4.class)
public class NavigationCharactersActivityTest {

    @Rule
    public RuleChain rules = RuleChain.emptyRuleChain()
            .around(new MockWebServerRule(this))
            .around(new ActivityTestRule<NavigationActivity>(NavigationActivity.class) {

                /**
                 * To avoid conflicts and work with the same data each time we call
                 * {@link com.example.android0128.trainingmvp.data.db.CharacterLocalDataSource#deleteAllCharacters()}
                 * before each test.
                 */
                @Override
                protected void beforeActivityLaunched() {
                    super.beforeActivityLaunched();
                    // Doing this in @Before generates a race condition.
                    (new FavoriteCharacters()).deleteAllCharacters();
                }
            });

    private ItemsScreen itemsScreen;

    @Before
    public void beforeEachTest() {
        itemsScreen = new ItemsScreen();
        //(new FavoriteCharacters()).deleteAllCharacters();
    }

    //TODO Don't get from ws
    /**
     * @see #shouldDisplayAllItemsFromSuccessfulResponse_setupMockWebServer(MockWebServer)
     */
    @Test
    @NeedsMockWebServer(setupMethod = "shouldDisplayAllItemsFromSuccessfulResponse_setupMockWebServer")
    public void navigationCharactersActivityTest() throws InterruptedException {
        Thread.sleep(3000);

        ViewInteraction recyclerView = onView(
                allOf(withId(R.id.list),
                        withParent(allOf(withId(R.id.refresh),
                                withParent(withId(R.id.viewpager)))),
                        isDisplayed()));
        recyclerView.perform(actionOnItemAtPosition(0, click()));

        ViewInteraction textView = onView(
                allOf(withId(R.id.tv_name), withText("3-D Man"),
                        childAtPosition(
                                childAtPosition(
                                        withId(R.id.activity_character_detail),
                                        0),
                                0),
                        isDisplayed()));
        textView.check(matches(withText("3-D Man")));

        ViewInteraction appCompatImageView = onView(
                withId(R.id.iv_favorite));
        appCompatImageView.perform(scrollTo(), click());

        pressBack();

        //Check favorite is shown
        ViewInteraction imageView = onView(
                allOf(withId(R.id.iv_favorite),
                        childAtPosition(
                                IsInstanceOf.<View>instanceOf(android.widget.RelativeLayout.class),
                                1),
                        isDisplayed()));
        imageView.check(matches(isDisplayed()));

        //Go to Favorite Tab by click
        ViewInteraction appCompatTextView = onView(
                allOf(withText("Favorites"), isDisplayed()));
        appCompatTextView.perform(click());

        //Go to All Tab by swipe
        ViewInteraction viewPager = onView(
                allOf(withId(R.id.viewpager), isDisplayed()));
        viewPager.perform(swipeLeft());

        ViewInteraction textView2 = onView(
                allOf(withId(R.id.tv_content), withText("3-D Man"),
                        isDisplayed()));
        textView2.check(matches(withText("3-D Man")));

        ViewInteraction appCompatTextView2 = onView(
                allOf(withText("All"), isDisplayed()));
        appCompatTextView2.perform(click());

        ViewInteraction viewPager2 = onView(
                allOf(withId(R.id.viewpager), isDisplayed()));
        viewPager2.perform(swipeRight());

        ViewInteraction appCompatTextView3 = onView(
                allOf(withText("Favorites"), isDisplayed()));
        appCompatTextView3.perform(click());

        ViewInteraction viewPager3 = onView(
                allOf(withId(R.id.viewpager), isDisplayed()));
        viewPager3.perform(swipeLeft());

        ViewInteraction recyclerView2 = onView(
                allOf(withId(R.id.list),
                        withParent(allOf(withId(R.id.refresh),
                                withParent(withId(R.id.viewpager)))),
                        isDisplayed()));
        recyclerView2.perform(actionOnItemAtPosition(0, click()));

        ViewInteraction appCompatImageView2 = onView(
                withId(R.id.iv_favorite));
        appCompatImageView2.perform(scrollTo(), click());

        pressBack();

        ViewInteraction recyclerView3 = onView(
                allOf(withId(R.id.list),
                        isDisplayed()));
        recyclerView3.check(matches(isDisplayed()));

        ViewInteraction appCompatTextView4 = onView(
                allOf(withText("All"), isDisplayed()));
        appCompatTextView4.perform(click());

        ViewInteraction viewPager4 = onView(
                allOf(withId(R.id.viewpager), isDisplayed()));
        viewPager4.perform(swipeRight());

        ViewInteraction textView3 = onView(
                allOf(withId(R.id.tv_content), withText("3-D Man"),
                        isDisplayed()));
        textView3.check(matches(withText("3-D Man")));

    }

    private static Matcher<View> childAtPosition(
            final Matcher<View> parentMatcher, final int position) {

        return new TypeSafeMatcher<View>() {
            @Override
            public void describeTo(Description description) {
                description.appendText("Child at position " + position + " in parent ");
                parentMatcher.describeTo(description);
            }

            @Override
            public boolean matchesSafely(View view) {
                ViewParent parent = view.getParent();
                return parent instanceof ViewGroup && parentMatcher.matches(parent)
                        && view.equals(((ViewGroup) parent).getChildAt(position));
            }
        };
    }

    /**
     * @see #shouldDisplayAllItemsFromSuccessfulResponse_setupMockWebServer(MockWebServer)
     */
    //@Test
    //@NeedsMockWebServer(setupMethod = "shouldDisplayAllItemsFromSuccessfulResponse_setupMockWebServer")
    //public void shouldDisplayAllItemsFromSuccessfulResponse() {
        /*itemsScreen.shouldDisplayExpectedAmountOfItems(8);

        for (int i = 1; i < 9; i++) {
            itemsScreen
                    .shouldDisplayItemWithFavorite("Test title " + i)
                    .shouldDisplayItemWithShortDescription("Short desc " + i);
        }*/
    //}

    /**
     * @see #shouldDisplayAllItemsFromSuccessfulResponse()
     */
    public void shouldDisplayAllItemsFromSuccessfulResponse_setupMockWebServer(@NonNull MockWebServer mockWebServer) {
        mockWebServer.enqueue(new MockResponse().setBody("{\n" +
                "\"code\":200,\n" +
                "\"status\":\"Ok\",\n" +
                "\"copyright\":\"© 2017 MARVEL\",\n" +
                "\"attributionText\":\"Data provided by Marvel. © 2017 MARVEL\",\n" +
                "\"attributionHTML\":\"<a href=\\\"http://marvel.com\\\">Data provided by Marvel. © 2017 MARVEL</a>\",\n" +
                "\"etag\":\"1e3fa6d41033e2bed8e493e34811a219d41f20f7\",\n" +
                "\"data\":{\n" +
                "\"offset\":0,\n" +
                "\"limit\":12,\n" +
                "\"total\":1485,\n" +
                "\"count\":12,\n" +
                "\"results\":[\n" +
                "{\n" +
                "\"id\":1011334,\n" +
                "\"name\":\"3-D Man\",\n" +
                "\"description\":\"\",\n" +
                "\"modified\":\"2014-04-29T14:18:17-0400\",\n" +
                "\"thumbnail\":{\n" +
                "\"path\":\"http://i.annihil.us/u/prod/marvel/i/mg/c/e0/535fecbbb9784\",\n" +
                "\"extension\":\"jpg\"\n" +
                "},\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/characters/1011334\",\n" +
                "\"comics\":{\n" +
                "\"available\":12,\n" +
                "\"collectionURI\":\"http://gateway.marvel.com/v1/public/characters/1011334/comics\",\n" +
                "\"items\":[\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/comics/21366\",\n" +
                "\"name\":\"Avengers: The Initiative (2007) #14\"\n" +
                "},\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/comics/24571\",\n" +
                "\"name\":\"Avengers: The Initiative (2007) #14 (SPOTLIGHT VARIANT)\"\n" +
                "},\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/comics/21546\",\n" +
                "\"name\":\"Avengers: The Initiative (2007) #15\"\n" +
                "},\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/comics/21741\",\n" +
                "\"name\":\"Avengers: The Initiative (2007) #16\"\n" +
                "},\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/comics/21975\",\n" +
                "\"name\":\"Avengers: The Initiative (2007) #17\"\n" +
                "},\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/comics/22299\",\n" +
                "\"name\":\"Avengers: The Initiative (2007) #18\"\n" +
                "},\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/comics/22300\",\n" +
                "\"name\":\"Avengers: The Initiative (2007) #18 (ZOMBIE VARIANT)\"\n" +
                "},\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/comics/22506\",\n" +
                "\"name\":\"Avengers: The Initiative (2007) #19\"\n" +
                "},\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/comics/8500\",\n" +
                "\"name\":\"Deadpool (1997) #44\"\n" +
                "},\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/comics/10223\",\n" +
                "\"name\":\"Marvel Premiere (1972) #35\"\n" +
                "},\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/comics/10224\",\n" +
                "\"name\":\"Marvel Premiere (1972) #36\"\n" +
                "},\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/comics/10225\",\n" +
                "\"name\":\"Marvel Premiere (1972) #37\"\n" +
                "}\n" +
                "],\n" +
                "\"returned\":12\n" +
                "},\n" +
                "\"series\":{\n" +
                "\"available\":3,\n" +
                "\"collectionURI\":\"http://gateway.marvel.com/v1/public/characters/1011334/series\",\n" +
                "\"items\":[\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/series/1945\",\n" +
                "\"name\":\"Avengers: The Initiative (2007 - 2010)\"\n" +
                "},\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/series/2005\",\n" +
                "\"name\":\"Deadpool (1997 - 2002)\"\n" +
                "},\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/series/2045\",\n" +
                "\"name\":\"Marvel Premiere (1972 - 1981)\"\n" +
                "}\n" +
                "],\n" +
                "\"returned\":3\n" +
                "},\n" +
                "\"stories\":{\n" +
                "\"available\":21,\n" +
                "\"collectionURI\":\"http://gateway.marvel.com/v1/public/characters/1011334/stories\",\n" +
                "\"items\":[\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/stories/19947\",\n" +
                "\"name\":\"Cover #19947\",\n" +
                "\"type\":\"cover\"\n" +
                "},\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/stories/19948\",\n" +
                "\"name\":\"The 3-D Man!\",\n" +
                "\"type\":\"interiorStory\"\n" +
                "},\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/stories/19949\",\n" +
                "\"name\":\"Cover #19949\",\n" +
                "\"type\":\"cover\"\n" +
                "},\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/stories/19950\",\n" +
                "\"name\":\"The Devil's Music!\",\n" +
                "\"type\":\"interiorStory\"\n" +
                "},\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/stories/19951\",\n" +
                "\"name\":\"Cover #19951\",\n" +
                "\"type\":\"cover\"\n" +
                "},\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/stories/19952\",\n" +
                "\"name\":\"Code-Name: The Cold Warrior!\",\n" +
                "\"type\":\"interiorStory\"\n" +
                "},\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/stories/47184\",\n" +
                "\"name\":\"AVENGERS: THE INITIATIVE (2007) #14\",\n" +
                "\"type\":\"cover\"\n" +
                "},\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/stories/47185\",\n" +
                "\"name\":\"Avengers: The Initiative (2007) #14 - Int\",\n" +
                "\"type\":\"interiorStory\"\n" +
                "},\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/stories/47498\",\n" +
                "\"name\":\"AVENGERS: THE INITIATIVE (2007) #15\",\n" +
                "\"type\":\"cover\"\n" +
                "},\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/stories/47499\",\n" +
                "\"name\":\"Avengers: The Initiative (2007) #15 - Int\",\n" +
                "\"type\":\"interiorStory\"\n" +
                "},\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/stories/47792\",\n" +
                "\"name\":\"AVENGERS: THE INITIATIVE (2007) #16\",\n" +
                "\"type\":\"cover\"\n" +
                "},\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/stories/47793\",\n" +
                "\"name\":\"Avengers: The Initiative (2007) #16 - Int\",\n" +
                "\"type\":\"interiorStory\"\n" +
                "},\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/stories/48361\",\n" +
                "\"name\":\"AVENGERS: THE INITIATIVE (2007) #17\",\n" +
                "\"type\":\"cover\"\n" +
                "},\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/stories/48362\",\n" +
                "\"name\":\"Avengers: The Initiative (2007) #17 - Int\",\n" +
                "\"type\":\"interiorStory\"\n" +
                "},\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/stories/49103\",\n" +
                "\"name\":\"AVENGERS: THE INITIATIVE (2007) #18\",\n" +
                "\"type\":\"cover\"\n" +
                "},\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/stories/49104\",\n" +
                "\"name\":\"Avengers: The Initiative (2007) #18 - Int\",\n" +
                "\"type\":\"interiorStory\"\n" +
                "},\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/stories/49106\",\n" +
                "\"name\":\"Avengers: The Initiative (2007) #18, Zombie Variant - Int\",\n" +
                "\"type\":\"interiorStory\"\n" +
                "},\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/stories/49888\",\n" +
                "\"name\":\"AVENGERS: THE INITIATIVE (2007) #19\",\n" +
                "\"type\":\"cover\"\n" +
                "},\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/stories/49889\",\n" +
                "\"name\":\"Avengers: The Initiative (2007) #19 - Int\",\n" +
                "\"type\":\"interiorStory\"\n" +
                "},\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/stories/54371\",\n" +
                "\"name\":\"Avengers: The Initiative (2007) #14, Spotlight Variant - Int\",\n" +
                "\"type\":\"interiorStory\"\n" +
                "}\n" +
                "],\n" +
                "\"returned\":20\n" +
                "},\n" +
                "\"events\":{\n" +
                "\"available\":1,\n" +
                "\"collectionURI\":\"http://gateway.marvel.com/v1/public/characters/1011334/events\",\n" +
                "\"items\":[\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/events/269\",\n" +
                "\"name\":\"Secret Invasion\"\n" +
                "}\n" +
                "],\n" +
                "\"returned\":1\n" +
                "},\n" +
                "\"urls\":[\n" +
                "{\n" +
                "\"type\":\"detail\",\n" +
                "\"url\":\"http://marvel.com/characters/74/3-d_man?utm_campaign=apiRef&utm_source=efcb8d31f5ea78d75d02d55ed49db6d8\"\n" +
                "},\n" +
                "{\n" +
                "\"type\":\"wiki\",\n" +
                "\"url\":\"http://marvel.com/universe/3-D_Man_(Chandler)?utm_campaign=apiRef&utm_source=efcb8d31f5ea78d75d02d55ed49db6d8\"\n" +
                "},\n" +
                "{\n" +
                "\"type\":\"comiclink\",\n" +
                "\"url\":\"http://marvel.com/comics/characters/1011334/3-d_man?utm_campaign=apiRef&utm_source=efcb8d31f5ea78d75d02d55ed49db6d8\"\n" +
                "}\n" +
                "]\n" +
                "},\n" +
                "{\n" +
                "\"id\":1017100,\n" +
                "\"name\":\"A-Bomb (HAS)\",\n" +
                "\"description\":\"Rick Jones has been Hulk's best bud since day one, but now he's more than a friend...he's a teammate! Transformed by a Gamma energy explosion, A-Bomb's thick, armored skin is just as strong and powerful as it is blue. And when he curls into action, he uses it like a giant bowling ball of destruction! \",\n" +
                "\"modified\":\"2013-09-18T15:54:04-0400\",\n" +
                "\"thumbnail\":{\n" +
                "\"path\":\"http://i.annihil.us/u/prod/marvel/i/mg/3/20/5232158de5b16\",\n" +
                "\"extension\":\"jpg\"\n" +
                "},\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/characters/1017100\",\n" +
                "\"comics\":{\n" +
                "\"available\":0,\n" +
                "\"collectionURI\":\"http://gateway.marvel.com/v1/public/characters/1017100/comics\",\n" +
                "\"items\":[\n" +
                "],\n" +
                "\"returned\":0\n" +
                "},\n" +
                "\"series\":{\n" +
                "\"available\":0,\n" +
                "\"collectionURI\":\"http://gateway.marvel.com/v1/public/characters/1017100/series\",\n" +
                "\"items\":[\n" +
                "],\n" +
                "\"returned\":0\n" +
                "},\n" +
                "\"stories\":{\n" +
                "\"available\":1,\n" +
                "\"collectionURI\":\"http://gateway.marvel.com/v1/public/characters/1017100/stories\",\n" +
                "\"items\":[\n" +
                "{\n" +
                "\"resourceURI\":\"http://gateway.marvel.com/v1/public/stories/105929\",\n" +
                "\"name\":\"cover from Free Comic Book Day 2013 (Avengers/Hulk) (2013) #1\",\n" +
                "\"type\":\"cover\"\n" +
                "}\n" +
                "],\n" +
                "\"returned\":1\n" +
                "},\n" +
                "\"events\":{\n" +
                "\"available\":0,\n" +
                "\"collectionURI\":\"http://gateway.marvel.com/v1/public/characters/1017100/events\",\n" +
                "\"items\":[\n" +
                "],\n" +
                "\"returned\":0\n" +
                "},\n" +
                "\"urls\":[\n" +
                "{\n" +
                "\"type\":\"detail\",\n" +
                "\"url\":\"http://marvel.com/characters/76/a-bomb?utm_campaign=apiRef&utm_source=efcb8d31f5ea78d75d02d55ed49db6d8\"\n" +
                "},\n" +
                "{\n" +
                "\"type\":\"comiclink\",\n" +
                "\"url\":\"http://marvel.com/comics/characters/1017100/a-bomb_has?utm_campaign=apiRef&utm_source=efcb8d31f5ea78d75d02d55ed49db6d8\"\n" +
                "}\n" +
                "]\n" +
                "}\n" +
                "]\n" +
                "}\n" +
                "}"));
    }
}
